Updated WinForms-PDFViewer-Examples
SyncfusionExamples/WinForms-PDFViewer-Examples pull request #8
Opened 2024-08-27 04:18 UTC by YathavakrishnanMohan

Description :
Update the Winforms-PDFViewer-Examples in .NETCore and .NETFramework

2024-10-03 07:54 UTC, Vikassekar requested changes
Hi @YathavakrishnanMohan ,

please remove the commented lines.

Regards,
Vikas

2024-10-03 07:54 UTC, Vikassekar commented on Bookmarks Navigation/PDFBookmarks/PDFBookmarks/Properties/AssemblyInfo.cs
> -[assembly: AssemblyTitle("SampleWF")]
Remove the commented lines

2024-10-03 09:35 UTC, YathavakrishnanMohan commented on Bookmarks Navigation/PDFBookmarks/PDFBookmarks/Properties/AssemblyInfo.cs
> -[assembly: AssemblyTitle("SampleWF")]
Removed the commented lines completed

2024-10-22 10:39 UTC, Vikassekar approved these changes
Approving this

2024-10-22 10:41 UTC, merged